### ISSUE TITLE
Please consider renaming package format from APK

### ISSUE THREAD

**Issue by eMPee584** [postmarketOS/binary-package-repo#10]
It will just be a great source of confusion once this gets the much appreciated uptake.

**Comment by MartijnBraam** [comment]
The package format is from Alpine, not from postmarketOS so we can't really change it.

**Comment by eMPee584** [comment]
Ok.. well you could voice your opinion on it to the Alpine devs..
If and once this project gains traction, user numbers of alpine linux will be catapulted into different scales. It'd be "easy" to make this change now, only inconvenient for the developers who have become used to APK.
I propose ALX(.tgz) or AXP or something.

**Comment by ollieparanoid** [comment]
I get that it is confusing, but I doubt that Alpine wants to change the extension. They were even joking in IRC about adding support for Android's format in the *Alpine package keeper* (apk, the package manager, which has the same name) ;)

The good news is, that with a real Linux distribution, you won't download packages directly from the web anyway, only through your package manager from package repositories (where you have the package signing key imported). So it will be abstracted, and end-users will not really see the file extension.
