### ISSUE TITLE
AzPainter (software)

### ISSUE THREAD

**Issue by ghost** [postmarketOS/binary-package-repo#11]
Could you try build binary package of **AzPainter** for **postmarketOS**?

* http://github.com/symbian9/azpainter

REFERENCE:
* http://azsky2.html.xdomain.jp/linux/azpainter.html
* http://azsky2.html.xdomain.jp/memo/index.html

**Comment by ollieparanoid** [comment]
The binary package repo is WIP currently, and it is intended to build the packages from [aports](https://github.com/postmarketOS/pmbootstrap/tree/master/aports/) only.

However, the software you have linked already has an AUR package, so it should be quite easy to transform that PKGBUILD into an APKBUILD, which is Alpine's format for package build recipes.

**Here is a [guide](https://wiki.postmarketos.org/wiki/Create_a_package).** Please try it out, we will help you in the [chat](https://wiki.postmarketos.org/wiki/Matrix_and_IRC) if you run into problems. If you get stuck on a big problem, please open an issue in the [pmbootstrap](https://github.com/postmarketOS/pmbootstrap) repository.

See also: [only 5 commands to run postmarketOS in a QEMU virtual machine](https://postmarketos.org/blog/2017/09/03/100-days-of-postmarketos/#integrated-qemu-support).

Thank you for your interest in postmarketOS!
